package com.group10.sparkysbank.model;


// default package
// Generated Oct 26, 2014 3:05:06 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Pwdrecovery generated by hbm2java
 */
@Entity
@Table(name = "pwdrecovery", catalog = "sparkysbankdb")
public class Pwdrecovery implements java.io.Serializable {

	private int idpwdrecovery;
	private String username;
	private String question1;
	private String ans1;
	private String question2;
	private String ans2;

	public Pwdrecovery() {
	}

	public Pwdrecovery(int idpwdrecovery) {
		this.idpwdrecovery = idpwdrecovery;
	}

	public Pwdrecovery(int idpwdrecovery, String username, String question1,
			String ans1, String question2, String ans2) {
		this.idpwdrecovery = idpwdrecovery;
		this.username=username;
		this.question1 = question1;
		this.ans1 = ans1;
		this.question2 = question2;
		this.ans2 = ans2;
	}

	@Id
	@Column(name = "idpwdrecovery", unique = true, nullable = false)
	@GeneratedValue
	public int getIdpwdrecovery() {
		return this.idpwdrecovery;
	}

	public void setIdpwdrecovery(int idpwdrecovery) {
		this.idpwdrecovery = idpwdrecovery;
	}

	@Column(name="username")
	public String getUsername()
	{
		return this.username;
	}
	public void setUsername(String username)
	{
		this.username=username;
	}

	@Column(name = "question1")
	public String getQuestion1() {
		return this.question1;
	}

	public void setQuestion1(String question1) {
		this.question1 = question1;
	}

	@Column(name = "ans1")
	public String getAns1() {
		return this.ans1;
	}

	public void setAns1(String ans1) {
		this.ans1 = ans1;
	}

	@Column(name = "question2")
	public String getQuestion2() {
		return this.question2;
	}

	public void setQuestion2(String question2) {
		this.question2 = question2;
	}

	@Column(name = "ans2")
	public String getAns2() {
		return this.ans2;
	}

	public void setAns2(String ans2) {
		this.ans2 = ans2;
	}

}