package com.group10.sparkysbank.model;


// default package
// Generated Oct 26, 2014 3:05:06 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "transaction_types", catalog = "sparkysbankdb")
public class TransactionTypes implements java.io.Serializable {

	private String idtransactionTypes;

	public TransactionTypes() {
	}

	public TransactionTypes(String idtransactionTypes) {
		this.idtransactionTypes = idtransactionTypes;
	}


	@Id
	@Column(name = "idtransaction_types", unique = true, nullable = false, length = 45)
	public String getIdtransactionTypes() {
		return this.idtransactionTypes;
	}

	public void setIdtransactionTypes(String idtransactionTypes) {
		this.idtransactionTypes = idtransactionTypes;
	}


}
